#!/bin/bash

DIFF="$(git diff ..origin/test RELEASE.md)"

# exit with code 0 if length of DIFF is 0

if [ ${#DIFF} -eq 0 ]; then
    echo "No changes detected"
    exit 1
else
    echo "Changes detected"
    exit 0
fi