on:
  pull_request:
    branches:
      - test

jobs:
  check-diff-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: "Check diff"
        run: git diff --exit-code test..${{github.head_ref}}
