on:
  pull_request:
    branches:
      - test

jobs:
  check-diff-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - run: git fetch --all
        name: Fetching remote

      - name: "Check diff"
        run: |
          DIFF="$(git diff ..origin/test RELEASE.md)"

          if [ ${#DIFF} -eq 0 ]; then
              echo "No changes detected"
              exit 1
          else
              echo "Changes detected"
              exit 0
          fi
